from django.utils.translation import gettext_lazy as _

TIMEZONES = [
    (-43200, _("International Date Line West")),
    (-39600, _("Midway Island, Samoa")),
    (-36000, _("Hawaii")),
    (-34200, _("French Polynesia, Marquesas Islands")),
    (-32400, _("Alaska")),
    (-28800, _("Pacific Time (US & Canada)")),
    (-25200, _("Mountain Time (US & Canada)")),
    (-21600, _("Central Time (US & Canada), Guadalajara, Mexico City")),
    (-18000, _("Eastern time (US & Canada)")),
    (-16200, _("Not used for Venezuela")),
    (-14400, _("Atlantic time (Canada), Manaus, Santiago, Venezuela")),
    (-12600, _("Newfoundland")),
    (-10800, _("Greenland, Brasilia, Montevideo")),
    (-7200, _("Mid-Atlantic")),
    (-3600, _("Azores")),
    (0, _("GMT: Dublin, Edinburgh, Lisbon, London")),
    (3600, _("Amsterdam, Berlin, Rome, Vienna, Prague, Brussels")),
    (7200, _("Athens, Istanbul, Beirut, Cairo, Jerusalem, Kaliningrad")),
    (10800, _("Minsk, Nairobi, Moscow, Baghdad")),
    (12600, _("Iran")),
    (14400, _("Baku, Yerevan, Izhevsk, Samara")),
    (16200, _("Afghanistan")),
    (18000, _("Astana, Ekaterinburg, Tashkent")),
    (19800, _("Chennai, Kolkata, Mumbai, New Delhi")),
    (20700, _("Nepal")),
    (21600, _("Dhaka, Omsk")),
    (23400, _("Myanmar, Cocos Islands")),
    (25200, _("Bangkok, Hanoi, Jakarta, Krasnoyarsk, Kemerovo, Novosibirsk")),
    (28800, _("Ulaanbaatar, Perth, Irkutsk, Chita, Kuala Lumpur")),
    (32400, _("Japan Standard Time, Yakutsk")),
    (34200, _("Australian Central Standard Time")),
    (36000, _("Canberra, Melbourne, Sydney, Hobart, Vladivostok, Magadan")),
    (37800, _("Lord Howe Standard Time")),
    (39600, _("Solomon Is., New Caledonia, Chokurdakh, Sakhalin")),
    (43200, _("Auckland, Wellington, Anadyr, Petropavlovsk-Kamchatsky")),
    (45900, _("New Zealand, Chatham Island")),
    (46800, _("Nuku'alofa")),
    (50400, _("Kiribati, Line Islands")),
]
