# Generated by Django 6.0.5 on 2026-05-29 18:18

import django.db.models.deletion
import encrypted_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_count', models.PositiveIntegerField(default=0)),
                ('messages_limit', models.PositiveIntegerField(default=500)),
                ('token', encrypted_field.fields.EncryptedField(blank=True, default=None, null=True)),
                ('profile_id', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('merchant_id', models.CharField(blank=True, max_length=50)),
                ('subscription_id', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
