# Generated by Django 6.0.2 on 2026-02-16 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifier', '0001_initial'),
        ('terminusgps_payments', '0003_alter_subscription_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminusgpsnotifiercustomer',
            name='subscription',
            field=models.ForeignKey(blank=True, default=None, help_text='Select an Authorizenet subscription from the list.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifier_customer', to='terminusgps_payments.subscription'),
        ),
        migrations.AlterField(
            model_name='terminusgpsnotifiercustomer',
            name='token',
            field=models.OneToOneField(blank=True, default=None, help_text='Select a Wialon API token from the list.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifier_customer', to='terminusgps_notifier.wialontoken'),
        ),
    ]
