# Generated by Django 6.0.4 on 2026-04-14 17:20

import encrypted_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminusgpsnotifiercustomer',
            name='token',
            field=encrypted_field.fields.EncryptedField(blank=True),
        ),
    ]
