# Generated by Django 6.0.5 on 2026-06-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('unit_id', models.IntegerField()),
                ('message', models.CharField(max_length=1024)),
                ('msg_time_int', models.IntegerField()),
                ('dry_run', models.BooleanField()),
                ('unit_name', models.CharField(blank=True)),
                ('location', models.CharField(blank=True)),
                ('date_format', models.CharField(blank=True, default='%Y-%m-%d %H:%M:%S')),
            ],
            options={
                'verbose_name': 'dispatch log',
                'verbose_name_plural': 'dispatch logs',
            },
        ),
    ]
