# Generated by Django 6.0.5 on 2026-06-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifier', '0002_dispatchlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchlog',
            name='date_format',
        ),
        migrations.RemoveField(
            model_name='dispatchlog',
            name='dry_run',
        ),
        migrations.RemoveField(
            model_name='dispatchlog',
            name='location',
        ),
        migrations.RemoveField(
            model_name='dispatchlog',
            name='unit_name',
        ),
    ]
