# Generated by Django 6.0.4 on 2026-04-14 17:24

import encrypted_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifier', '0002_terminusgpsnotifiercustomer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminusgpsnotifiercustomer',
            name='token',
            field=encrypted_field.fields.EncryptedField(blank=True, default=None, null=True),
        ),
    ]
