# Generated by Django 6.0.5 on 2026-05-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifier', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='checkout_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='customer_profile_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
