# Generated by Django 6.0.5 on 2026-06-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifier', '0003_remove_dispatchlog_date_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchlog',
            name='method',
            field=models.CharField(choices=[('sms', 'SMS'), ('voice', 'Voice')], default='sms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatchlog',
            name='phones',
            field=models.JSONField(default=list),
        ),
    ]
