# Generated by Django 6.0.4 on 2026-04-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifier', '0003_alter_terminusgpsnotifiercustomer_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wialonnotification',
            name='resource',
        ),
        migrations.DeleteModel(
            name='WialonUnit',
        ),
        migrations.DeleteModel(
            name='WialonUnitGroup',
        ),
        migrations.AlterModelOptions(
            name='wialonnotification',
            options={'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='ac',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='act',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='cdt',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='ct',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='ctrl_sch',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='d',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='e',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='fl',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='la',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='ma',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='mast',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='mmtd',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='mpst',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='mt',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='n',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='sch',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='ta',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='td',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='trg',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='txt',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='tz',
        ),
        migrations.RemoveField(
            model_name='wialonnotification',
            name='un',
        ),
        migrations.DeleteModel(
            name='WialonResource',
        ),
    ]
