# Generated by Django 6.0.5 on 2026-05-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifier', '0003_remove_profile_checkout_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='customer_profile_id',
        ),
    ]
