# Generated by Django 6.0.6 on 2026-06-08 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifier', '0004_dispatchlog_method_dispatchlog_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchlog',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
