# Generated by Django 6.0.4 on 2026-04-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifier', '0004_remove_wialonnotification_resource_delete_wialonunit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WialonNotification',
        ),
    ]
