# Generated by Django 6.0.4 on 2026-04-20 15:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifier', '0006_alter_terminusgpsnotifiercustomer_user'),
        ('terminusgps_payments', '0002_subscription_expires_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TerminusGPSNotifierCustomer',
            new_name='Customer',
        ),
    ]
