# Generated by Django 6.0.4 on 2026-05-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifier', '0007_rename_terminusgpsnotifiercustomer_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='subscription',
        ),
        migrations.AddField(
            model_name='customer',
            name='subscription_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
