# Generated by Django 6.0.4 on 2026-05-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifier', '0008_remove_customer_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
