# Generated by Django 6.0.4 on 2026-05-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifier', '0009_customer_subscription_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='subscription_expiry',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_profile_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
