# Generated by Django 6.0.4 on 2026-05-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifier', '0010_remove_customer_subscription_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_profile_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='stripe_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
