# Generated by Django 6.0.4 on 2026-05-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifier', '0011_remove_customer_customer_profile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='checkout_id',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
